# Create a Fly.io app and deploy a Docker image from a GitHub repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t impulse-bot-chatbot \
          --build-arg DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" \
          --build-arg OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" .
        working-directory: ./app

      - name: Push the Docker image
        run: docker push impulse-bot-chatbot

  deploy_to_fly:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Fly CLI
        run: |
          wget https://fly.io/install.sh
          chmod +x install.sh
          ./install.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: fly deploy --config fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
